### ISSUE TITLE
Failing on comparing yang modules. 

### ISSUE THREAD

**Issue by ahassany** [HuaweiDatacomm/yang-comparator#2]
I've tried the yang-comparator built from master. I got the following exception, and not sure why? I attached the yang modules I'm trying to compare: [qos-yang.zip](https://github.com/HuaweiDatacomm/yang-comparator/files/10871957/qos-yang.zip)

```
java -jar target/yang-comparator-1.1.0.jar -left --y ./qos-yang/662 -right --y ./qos-yang/781 -o out/output.xml -stmt
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.yangcentral.yangkit.common.api.Namespace.equals(Object)" because the return value of "org.yangcentral.yangkit.base.YangContext.getNamespace()" is null
	at com.huawei.yang.comparator.CommonYangStatementComparator.yangStatementIsEqual(CommonYangStatementComparator.java:282)
	at com.huawei.yang.comparator.CommonYangStatementComparator.searchStatement(CommonYangStatementComparator.java:205)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:118)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:170)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:124)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:170)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:84)
	at com.huawei.yang.comparator.YangComparator.compareStatement(YangComparator.java:188)
	at com.huawei.yang.comparator.YangComparator.compare(YangComparator.java:419)
	at com.huawei.yang.comparator.YangComparator.main(YangComparator.java:606)
```

**Comment by lllyfeng** [comment]
Ahmed，it's lack of dependent module :Cisco-IOS-XR-types.  I suggest you use yang-compiler with yang-comparator plugin, yang-compiler can download dependencies automatically.

**Comment by ahassany** [comment]
Thank you for the input. I'm still having troubles running the yang-compiler. But I'll report these issue on it's repo.
