### ISSUE TITLE
Failing to compare ietf-yang-types

### ISSUE THREAD

**Issue by ahassany** [HuaweiDatacomm/yang-comparator#6]
I tried to compare the two versions of ietf-yang-types [2010-09-24](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-yang-types%402010-09-24.yang) and [2013-07-15](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-yang-types%402013-07-15.yang) but I got a strange exception.

I downloaded the two versions and put them on v1 and v2 then ran the following command 
```java -jar target/yang-comparator-1.1.0.jar -left --y v1  -right --y  v2 -o out/output.xml -compatible-check```

and I got the same error running the comparison comparing the model to itself.
```java -jar target/yang-comparator-1.1.0.jar -left --y v2  -right --y  v2 -o out/output.xml -compatible-check```

```
Exception in thread "main" java.lang.ClassCastException: class org.yangcentral.yangkit.base.YangComment cannot be cast to class org.yangcentral.yangkit.model.api.stmt.YangBuiltinStatement (org.yangcentral.yangkit.base.YangComment and org.yangcentral.yangkit.model.api.stmt.YangBuiltinStatement are in unnamed module of loader 'app')
	at org.yangcentral.yangkit.model.impl.stmt.ModuleImpl.initSelf(ModuleImpl.java:738)
	at org.yangcentral.yangkit.model.impl.stmt.MainModuleImpl.initSelf(MainModuleImpl.java:51)
	at org.yangcentral.yangkit.model.impl.stmt.YangStatementImpl.init(YangStatementImpl.java:806)
	at org.yangcentral.yangkit.model.impl.schema.YangSchemaContextImpl.validate(YangSchemaContextImpl.java:286)
	at com.huawei.yang.comparator.app.YangComparatorRunner.main(YangComparatorRunner.java:145)
```

**Comment by lllyfeng** [comment]
I have not found this issue. Perhaps you should update the latest code from yangkit project.

**Comment by ahassany** [comment]
I will double check on a clean system .. could be an issue of my local setup

**Comment by ahassany** [comment]
This is a local issue in my setup
